import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styled from "styled-components";
import { GiHamburgerMenu } from "react-icons/gi";
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { FaPaypal, FaCcMastercard, FaCcVisa, FaCcAmex } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home JUWA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <GiHamburgerMenu color="#fff" size="2rem" />
        <h1>JUWA</h1>
        <LoginButton>Sign in</LoginButton>
      </Header>
      <Container>
        <Carousel
          className="custom-carousel"
          showThumbs={true}
          showStatus={false}
          autoPlay={false}
          infiniteLoop={true}
          interval={3000}
          renderThumbs={() => {
            return [
              <Thumbnails key="first" color="#80ff00">
                <p>EXKLUSIVE</p>
                <p>TOP BEWERTETE</p>
                <h2>SLOTS</h2>
                <LoginButton backgroundColor="#80ff00" className="mt-2">
                  Jetzt Anmelden
                </LoginButton>
                <small className="underline mt-4 text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </Thumbnails>,
              <Thumbnails key="second" color="#0080ff">
                <p>SPANNENDES</p>
                <h2>POKER</h2>
                <p>SPANNUNG PUR</p>
                <LoginButton backgroundColor="#0080ff" className="mt-2">
                  Jetzt Anmelden
                </LoginButton>
                <small className="underline mt-4 text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </Thumbnails>,
              <Thumbnails key="thirid" color="#fa6200">
                <p>HOCHWERTIGE</p>
                <h2>SPORTWETTEN</h2>
                <p>TOLLE PROMOTIONS</p>
                <LoginButton backgroundColor="#fa6200" className="mt-2">
                  Jetzt Anmelden
                </LoginButton>
                <small className="underline mt-4 text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </Thumbnails>,
            ];
          }}
        >
          <div className="relative">
            <BanerText color="#80ff00">
              <div className="flex gap-5">
                <GameImage>
                  <img src="https://toaster.images4us.com/20211008/logo-slots.svg" />
                </GameImage>
                <div className="bg-[#80ff00] w-[0.22vw]"> </div>
                <div className="text-left">
                  <p>EXKLUSIVE</p>
                  <p>TOP BEWERTETE</p>
                  <h2>SLOTS</h2>
                </div>
              </div>
              <div className="flex flex-col justify-center align-middle w-fit">
                <BannerLogin className="mt-2">Jetzt Anmelden</BannerLogin>
                <small className="underline text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </div>
            </BanerText>
            <video
              src="https://toaster.images4us.com/20211021/PC_BG_Casino-de.mp4"
              autoPlay
              loop
              muted
            />
          </div>
          <div className="relative">
            <BanerText color="#0080ff">
              <div className="flex gap-5">
                <GameImage>
                  <img src="https://toaster.images4us.com/20211008/logo-poker.svg" />
                </GameImage>
                <div className="bg-[#0080ff] w-[0.22vw]"> </div>
                <div className="text-left">
                  <p>SPANNENDES</p>
                  <h2>POKER</h2>
                  <p>SPANNUNG PUR</p>
                </div>
              </div>
              <div className="flex flex-col justify-center align-middle w-fit">
                <BannerLogin className="mt-2">Jetzt Anmelden</BannerLogin>
                <small className="underline text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </div>
            </BanerText>
            <video
              src="https://toaster.images4us.com/20211018/PC_Poker.mp4"
              autoPlay
              loop
              muted
            />
          </div>
          <div className="relative">
            <BanerText color="#fa6200">
              <div className="flex gap-5">
                <GameImage>
                  <img src="https://toaster.images4us.com/20211012/logo-sport.svg" />
                </GameImage>
                <div className="bg-[#fa6200] w-[0.22vw]"> </div>
                <div className="text-left">
                  <p>HOCHWERTIGE</p>
                  <h2>SPORTWETTEN</h2>
                  <p>TOLLE PROMOTIONS</p>
                </div>
              </div>
              <div className="flex flex-col justify-center align-middle w-fit">
                <BannerLogin className="mt-2">Jetzt Anmelden</BannerLogin>
                <small className="underline text-[#666] hover:text-[#fff] cursor-pointer relative z-10">
                  Bonusregelung
                </small>
              </div>
            </BanerText>
            <Image
              src="https://images.images4us.com/888_DE_V2/DE/1920_PC_Sport_new-1634039410127_tcm2024-532027.jpg"
              alt="Image 2"
              width={1920}
              height={1080}
            />
          </div>
        </Carousel>
        <main className="main">
          <AwardsSection>
            <SectionContainer>
              <h2 className="text-4xl m-4">Ehrungen & Auszeichnungen</h2>
              <p className="m-4">
                Exzellenz im Gaming ist unser Motto. Wenn Sie mit uns spielen,
                genießen Sie ein erstklassiges Erlebnis. 888 wurde von den
                weltweit führenden Behörden für Online-Glücksspiele
                ausgezeichnet und erhielt zahlreiche Auszeichnungen. Wir danken
                unseren treuen Spielern für ihre Unterstützung!
              </p>
              <div className="flex flex-wrap justify-center">
                <div className="w-1/2 md:w-1/4 p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-winner-of-egr-award-1631085867226_tcm2024-530324.png"
                    alt="Image 2"
                    width={300}
                    height={300}
                  />
                </div>
                <div className="w-1/2 md:w-1/4 p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-winner-of-50plus-international-awards-1631085906661_tcm2024-530326.png"
                    alt="Image 2"
                    width={300}
                    height={300}
                  />
                </div>
                <div className="w-1/2 md:w-1/4 p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-winner-of-1st-gaming-intelligence-award-1631085937918_tcm2024-530327.png"
                    alt="Image 2"
                    width={300}
                    height={300}
                  />
                </div>
              </div>
              <div className="flex flex-wrap justify-center">
                <div className="w:fit-content p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-the-gaming-intelligence-gia-2016-awards-1631085974015_tcm2024-530328.png"
                    alt="Image 2"
                    width={130}
                    height={130}
                  />
                </div>
                <div className="w:fit-content p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-egr-awards-1631085996450_tcm2024-530329.png"
                    alt="Image 2"
                    width={130}
                    height={130}
                  />
                </div>
                <div className="w:fit-content p-4">
                  <Image
                    src="https://images.images4us.com/888_DE_V2/DE/888Holdings-global-gaming-awards-1631086016519_tcm2024-530330.png"
                    alt="Image 2"
                    width={130}
                    height={130}
                  />
                </div>
              </div>
            </SectionContainer>
          </AwardsSection>
        </main>
        <Footer>
          <div className="flex w-[100%] align-center justify-center bg-[#794b4b] gap-4">
            <FaPaypal size="2rem" />
            <FaCcMastercard size="2rem" />
            <FaCcVisa size="2rem" />
            <FaCcAmex size="2rem" />
          </div>
          <p className="text-center p-1">Impressum:</p>
          <p className="text-center p-4">
            Copyright 2023, the Juwa777. All rights reserved. Gambling should be
            entertaining. Remember that you always risk losing the money you
            bet, so do not spend more than you can afford to lose. If you think
            you may have a problem, click here.
          </p>
        </Footer>
      </Container>
    </>
  );
}

const Header = styled.header`
  background-color: #232323;
  color: #fff;
  border-bottom: 1px solid #eaeaea;
  width: 100%;
  height: 60px;
  max-height: 60px;
  min-height: 45px;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;
const Container = styled.div``;
interface ButtonProps {
  backgroundColor?: string;
}

const LoginButton = styled.button<ButtonProps>`
  color: ${(props) => props.backgroundColor || "white"};
  background-color: transparent;
  border: 2px solid ${(props) => props.backgroundColor || "white"};
  padding: 10px 20px;
  border-radius: 80px;
  cursor: pointer;
  transition: background-color 0.3s ease;

  &:hover {
    color: black;
    background-color: ${(props) => props.backgroundColor || "white"};
  }
`;
const BannerLogin = styled.button`
  display: block;
  background-color: #fce403;
  color: #000;
  border-color: #fce403;
  border-radius: 80px;
  line-height: 1;
  position: relative;
  cursor: pointer;
  font-size: 1.6vw;
  border-style: solid;
  border-width: 2px;
  padding: 0.8vw 2vw;
  font-weight: 500;
  transition: all 0.3s ease-in-out;
  max-width: 20vw;
  margin-left: 2rem;
  margin-top: 1rem;
  margin-bottom: 1rem;
  position: relative;
  z-index: 10;
`;
const Thumbnails = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 20px 10px;
  color: #fff;
  p {
    font-size: 1.2rem;
    font-weight: 700;
    margin: 0;
  }
  h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0;
    color: ${(props) => props.color || "#fff"};
  }
`;
const BanerText = styled.div`
  position: absolute;
  left: 2.4vw;
  top: 17.2%;
  color: #fff;

  p {
    text-align: left;
    font-size: 2vw;
    line-height: 1;
    margin: 0;
  }
  h2 {
    font-size: 4vw;
    line-height: 1;
    margin: 0;
    color: ${(props) => props.color || "#fff"};
  }
`;
const GameImage = styled.div`
  max-width: 12vw;
  min-width: 11.8vw;
`;
const AwardsSection = styled.section`
  text-align: center;
  background-size: cover;
  background-repeat: no-repeat;
  padding: 20px;
  color: #000;
  background-image: url("https://images.images4us.com/888_DE_V2/DE/awards-background-resized-1631012435578.jpg");
`;

const SectionContainer = styled.div`
  max-width: 1200px;
  margin: 0 auto;
`;

const Footer = styled.footer`
  background-color: #232323;
  color: #fff;
  border-top: 1px solid #eaeaea;
  width: 100%;
  min-height: 45px;
`;
